routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/template',function(){
// 	return view('template');
// });

// Route::get('/template1',function(){
// 	return view('template1');
// });

Route::get('/manual/run','TestController@update_url')->name('test.run');
//Route::get('/call-logs/audited-by-agents','CallLogController@audited_by_agents')->name('call.audited_agents');
// Route::get('/call-logs/search-form','CallLogController@search_form')->name('call.search_form');
Route::get('/call-logs/search','CallLogController@search')->name('call.search');
Route::post('/call-logs/tag','CallLogController@tag_call')->name('call.tag');

Route::get('/','SuperAdminController@index')->name('root');
Route::get('/admin','AdminController@index')->name('admin.index');

Route::get('/account','UserController@index')->name('user.index');
Route::put('/account/update','UserController@update_account')->name('user.update_account');
Route::put('/account/password/update','UserController@update_password')->name('user.update_password');

Route::get('/auditor','AuditorController@index')->name('auditor.index');
Route::get('/auditor/my-logs','AuditorController@my_call_logs')->name('auditor.my_call_logs');
Route::get('/auditor/my-logs/completed','AuditorController@my_call_logs_completed')->name('auditor.my_call_logs_completed');
Route::get('/auditor/my-logs/completed/{recording}','AuditorController@recording_completed')->name('auditor.recording_completed');
Route::get('/auditor/team-claimed','AuditorController@team_claimed_logs')->name('auditor.team_claimed');
Route::get('/auditor/my-logs/{recording}','AuditorController@recording')->name('auditor.recording');
Route::post('/auditor/my-logs/{ctr}/destroy','AuditorController@destroy_mylog')->name('auditor.destroy_mylog');
Route::post('/auditor/claim_call','AuditorController@claim_call')->name('auditor.claim_call');
Route::post('/auditor/search_claim_call','AuditorController@search_claim_call')->name('auditor.search_claim_call');
Route::post('/auditor/bulk_search_claim_call','AuditorController@bulk_search_claim_call')->name('auditor.bulk_search_claim_call');
Route::post('/auditor/bulk_claim','AuditorController@bulk_claim')->name('auditor.bulk_claim');
Route::post('/auditor/submit_audit','AuditorController@submit_audit')->name('auditor.submit_audit');
Route::get('/auditor/my-audits','AuditorController@audits_form_page')->name('auditor.my-audits');
Route::get('/auditor/count-audits','AuditorController@audits_form_page_count')->name('auditor.count-audits');
Route::get('/auditor/search-preference','AuditorController@search_preference')->name('auditor.search_preference');


Route::get('/reports','ReportController@index')->name('report.index');
Route::get('/reports/calllog-responses','ReportController@calllog_responses')->name('report.calllog_responses');
Route::get('/reports/auditors-hourly','ReportController@auditors_hourly')->name('report.auditors_hourly');
Route::post('/reports/auditors_hourly_content','ReportController@auditors_hourly_content')->name('report.auditors_hourly_content');
Route::post('/download/calllog-responses','DownloadController@downloadCallLogResponses')->name('dl.calllog_responses');

Route::resource('findings','FindingController')->only(['store']);

Route::get('/supervisor','SupervisorController@index')->name('supervisor.index');
// Route::get('/search-calls','SupervisorController@search_calls')->name('supervisor.search_calls');
// Route::get('/search','SupervisorController@search')->name('supervisor.search');
Route::post('/assign-calls','SupervisorController@assign_calls')->name('supervisor.assign_calls');
Route::get('/supervisor/manage-teams','SupervisorController@manage_teams')->name('supervisor.manage_teams');
Route::get('/supervisor/call-assignment-preference','SupervisorController@assign_preference')->name('supervisor.assign_preference');
Route::get('/supervisor/call-assignment-preference/{id}/edit','SupervisorController@assign_preference_edit')->name('supervisor.assign_preference_edit');
Route::get('/supervisor/call-assignment-preference/new','SupervisorController@assign_preference_new')->name('supervisor.assign_preference_new');
Route::post('/supervisor/call-assignment-preference/create','SupervisorController@assign_preference_create')->name('supervisor.assign_preference_create');
Route::post('/supervisor/call-assignment-preference/{id}/update','SupervisorController@assign_preference_update')->name('supervisor.assign_preference_update');

Route::get('/incident-report/form','IncidentReportController@form')->name('ir.form');


Route::resource('teams','TeamController')->only(['show','update','store','destroy']);

Route::resource('user_teams','UserTeamController')->only(['store','destroy']);

Route::get('/operation','OperationAuditorController@index')->name('ops.index');
Route::get('/operation/search/{type}','OperationAuditorController@search')->name('ops.search');
Route::get('/operation/audited/{recording}','OperationAuditorController@audited')->name('ops.audited');
Route::get('/operation/recordings/{ops_user}/{ctr}','OperationAuditorController@recording')->name('ops.recording');
Route::post('/operation/submit_audit','OperationAuditorController@submit_audit')->name('ops.submit_audit');
Route::get('/operation/my-audits','OperationAuditorController@my_audits')->name('ops.my_audits');
Route::delete('/operation/my-audits/{ctr}','OperationAuditorController@destroy_audit')->name('ops.destroy_audit');
Route::get('/operation/my-audits/{ctr}','OperationAuditorController@show')->name('ops.show');
Route::get('/operation/search-preference','OperationAuditorController@search_preference')->name('ops.search_preference');


Route::get('/incident-report','IncidentReportController@form')->name('ir.form');

Auth::routes();




// Route::resource('products','ProductController');

app/Models/Team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
	// specify custom primary key of the table
    // protected $primaryKey = 'code';

    protected $fillable = [
    	'name',
    	'short_desc',
    	'code'
    ];

    /*
    |-----------------------------
    |		Association
    |-----------------------------*/

    public function user_teams(){
        return $this->hasMany('App\Models\UserTeam','team_code','code');
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Models\Team;
use App\Models\User;
use App\Models\CallLogsAssigned;
use DB;

class TeamController extends Controller
{
    //
	public function store(Request $request){
		$request->validate([
			'name' => ['required','unique:teams']
		]);

		$team = Team::create([
					'name' => $request->name,
					'short_desc' => $request->short_desc
				]);
		$team->code = $team->id;
		$team->save();

		return redirect()->route('supervisor.manage_teams')
		                 ->with('success','Created new team');
	}

    public function show($team_id){
    	$team = Team::find($team_id);
    	$avail_users = User::no_team_users();

    	return view('team.show',compact('team','avail_users'));
    }

    public function update($team_id, Request $request){

    	$request->validate([
    		'name' => ['bail','required','unique:teams,code,'.$team_id]
    	]);

    	$team = Team::find($team_id);
    	$team->name = $request->name;
    	$team->short_desc = $request->short_desc;
    	$team->save();

    	return redirect()->route('teams.show',['team' => $team->code])
    					 ->with('success','Team\'s information has been updated');
    }

    public function destroy($team_id){
    	$team = Team::find($team_id); 	

    	// remove all responses from the recordings assigned by the calls assigned by that team and set them to available again
    	CallLogsAssigned::release_calls($team_id);

    	// unassign users from the team
    	foreach ($team->user_teams as $user) {
    		$user->delete();
    	}

    	// remove the team itself
    	$team->delete();

    	//session(['success'=>'Removed a team']);
    	Session::flash('success','Removed a team');
    }

}

resources/views/team/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="row">
		<div class="col-md-10 mx-auto">

			@if (session('success'))
			    <div class="alert alert-success alert-dismissible fade show">
			    	<button type="button" class="close" data-dismiss="alert">&times;</button>
			        <strong>Success! </strong>{{ session('success') }}
			    </div>
			@endif

			<div class="bg-notif rem-user-team-notif">
				<div class="card">
					<div class="card-header">
						Remove Member?
					</div>
					<div class="card-body">
						Are you sure you want to remove this member?
					</div>
					<div class="card-footer">
						<div class="d-flex justify-content-end">
							<button class="btn btn-primary rem-user-team px-4 mr-3">Yes</button>
							<button class="btn btn-secondary cancel">Cancel</button>
						</div>
					</div>
				</div>
			</div>

			<div class="box">
				<div class="right-back">
					<a href="{{ route('supervisor.manage_teams') }}">Back to Teams</a>
				</div>
				<h5>Team Information</h5>
				<form action="{{ route('teams.update',['team'=>$team->code]) }}" method="post">
					@csrf
					@method('put')
					<div class="row">
						<div class="col-md-3 mb-2">
							<div class="form-group my-0">
								<label>Team Name</label>
								<input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$team->name) }}">

								<span class="invalid-feedback feedback-inline" role="alert">
		                            @error('name') {{ $message }} @enderror
		                        </span>
							</div>
						</div>
						<div class="col-md-5 mb-2">
							<div class="form-group my-0">
								<label>Short Description</label>
								<input type="text" class="form-control" name="short_desc" value="{{ $team->short_desc }}">
							</div>
						</div>
						<div class="col-md-3 mb-2">
							<div class="d-flex h-100 align-items-end">
								<button class="btn btn-primary">Update</button>
							</div>
						</div>
					</div>
				</form>

				<div class="row">
					<div class="col-md-8">
						<div class="card mt-4">
							<div class="card-header">
								<h5 class="mr-auto">Members</h5>
							</div>
							<div class="card-body">
								<table class="table table-bordered table-responsive w-100 d-block d-md-table">
									@foreach($team->user_teams as $user)
									    <!-- 
									    	$user->id here is the id column in user_teams table 
									    -->
										<tr data-id="{{ $user->id }}">
											<td>{{ $user->user_name }}</td>
											<td><button class="btn btn-sm btn-danger rem-user-team-trg">Remove</button></td>
										</tr>
									@endforeach
								</table>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-8">
						<div class="card mt-4">
							<div class="card-header">
								<h5 class="mr-auto">Available Auditors</h5>
							</div>
							<div class="card-body">
								<table class="table table-bordered table-responsive w-100 d-block d-md-table">
									@if(count($avail_users))
										@foreach($avail_users as $avail_user)
											<tr data-id="{{ $avail_user->id }}" data-team="{{ $team->code }}">
												<td>{{ $avail_user->name }}</td>
												<td><button class="btn btn-sm btn-success px-3 add-user-team">Add</button></td>
											</tr>
										@endforeach
									@else
										<tr>
											<td class="text-center">No available auditors as of the moment</td>
										</tr>
									@endif
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection