routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/template',function(){
// 	return view('template');
// });

// Route::get('/template1',function(){
// 	return view('template1');
// });

Route::get('/manual/run','TestController@update_url')->name('test.run');
//Route::get('/call-logs/audited-by-agents','CallLogController@audited_by_agents')->name('call.audited_agents');
// Route::get('/call-logs/search-form','CallLogController@search_form')->name('call.search_form');
Route::get('/call-logs/search','CallLogController@search')->name('call.search');
Route::post('/call-logs/tag','CallLogController@tag_call')->name('call.tag');

Route::get('/','SuperAdminController@index')->name('root');
Route::get('/admin','AdminController@index')->name('admin.index');

Route::get('/account','UserController@index')->name('user.index');
Route::put('/account/update','UserController@update_account')->name('user.update_account');
Route::put('/account/password/update','UserController@update_password')->name('user.update_password');

Route::get('/auditor','AuditorController@index')->name('auditor.index');
Route::get('/auditor/my-logs','AuditorController@my_call_logs')->name('auditor.my_call_logs');
Route::get('/auditor/my-logs/completed','AuditorController@my_call_logs_completed')->name('auditor.my_call_logs_completed');
Route::get('/auditor/my-logs/completed/{recording}','AuditorController@recording_completed')->name('auditor.recording_completed');
Route::get('/auditor/team-claimed','AuditorController@team_claimed_logs')->name('auditor.team_claimed');
Route::get('/auditor/my-logs/{recording}','AuditorController@recording')->name('auditor.recording');
Route::post('/auditor/my-logs/{ctr}/destroy','AuditorController@destroy_mylog')->name('auditor.destroy_mylog');
Route::post('/auditor/claim_call','AuditorController@claim_call')->name('auditor.claim_call');
Route::post('/auditor/search_claim_call','AuditorController@search_claim_call')->name('auditor.search_claim_call');
Route::post('/auditor/bulk_search_claim_call','AuditorController@bulk_search_claim_call')->name('auditor.bulk_search_claim_call');
Route::post('/auditor/bulk_claim','AuditorController@bulk_claim')->name('auditor.bulk_claim');
Route::post('/auditor/submit_audit','AuditorController@submit_audit')->name('auditor.submit_audit');
Route::get('/auditor/my-audits','AuditorController@audits_form_page')->name('auditor.my-audits');
Route::get('/auditor/count-audits','AuditorController@audits_form_page_count')->name('auditor.count-audits');
Route::get('/auditor/search-preference','AuditorController@search_preference')->name('auditor.search_preference');


Route::get('/reports','ReportController@index')->name('report.index');
Route::get('/reports/calllog-responses','ReportController@calllog_responses')->name('report.calllog_responses');
Route::get('/reports/auditors-hourly','ReportController@auditors_hourly')->name('report.auditors_hourly');
Route::post('/reports/auditors_hourly_content','ReportController@auditors_hourly_content')->name('report.auditors_hourly_content');
Route::post('/download/calllog-responses','DownloadController@downloadCallLogResponses')->name('dl.calllog_responses');

Route::resource('findings','FindingController')->only(['store']);

Route::get('/supervisor','SupervisorController@index')->name('supervisor.index');
// Route::get('/search-calls','SupervisorController@search_calls')->name('supervisor.search_calls');
// Route::get('/search','SupervisorController@search')->name('supervisor.search');
Route::post('/assign-calls','SupervisorController@assign_calls')->name('supervisor.assign_calls');
Route::get('/supervisor/manage-teams','SupervisorController@manage_teams')->name('supervisor.manage_teams');
Route::get('/supervisor/call-assignment-preference','SupervisorController@assign_preference')->name('supervisor.assign_preference');
Route::get('/supervisor/call-assignment-preference/{id}/edit','SupervisorController@assign_preference_edit')->name('supervisor.assign_preference_edit');
Route::get('/supervisor/call-assignment-preference/new','SupervisorController@assign_preference_new')->name('supervisor.assign_preference_new');
Route::post('/supervisor/call-assignment-preference/create','SupervisorController@assign_preference_create')->name('supervisor.assign_preference_create');
Route::post('/supervisor/call-assignment-preference/{id}/update','SupervisorController@assign_preference_update')->name('supervisor.assign_preference_update');

Route::get('/incident-report/form','IncidentReportController@form')->name('ir.form');


Route::resource('teams','TeamController')->only(['show','update','store','destroy']);

Route::resource('user_teams','UserTeamController')->only(['store','destroy']);

Route::get('/operation','OperationAuditorController@index')->name('ops.index');
Route::get('/operation/search/{type}','OperationAuditorController@search')->name('ops.search');
Route::get('/operation/audited/{recording}','OperationAuditorController@audited')->name('ops.audited');
Route::get('/operation/recordings/{ops_user}/{ctr}','OperationAuditorController@recording')->name('ops.recording');
Route::post('/operation/submit_audit','OperationAuditorController@submit_audit')->name('ops.submit_audit');
Route::get('/operation/my-audits','OperationAuditorController@my_audits')->name('ops.my_audits');
Route::delete('/operation/my-audits/{ctr}','OperationAuditorController@destroy_audit')->name('ops.destroy_audit');
Route::get('/operation/my-audits/{ctr}','OperationAuditorController@show')->name('ops.show');
Route::get('/operation/search-preference','OperationAuditorController@search_preference')->name('ops.search_preference');


Route::get('/incident-report','IncidentReportController@form')->name('ir.form');

Auth::routes();




// Route::resource('products','ProductController');

app/Http/Controllers/SupervisorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\CallLog;
use App\Models\CallLogArchive;
use App\Models\CallLogsAssigned;
use App\Models\Team;
use App\Models\Server;
use App\Models\Campaign;
use App\Models\Disposition;
use App\Models\AssignPreference;
use App\Models\AssignPreferenceDisposition;
use App\Models\UserEmployeeMapping;
use DateTime;
use DateTimeZone;

class SupervisorController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index(Request $request){
    	$teams = Team::all();
    	// $servers = DB::table('calllogs')->distinct()->get('server_ip');
        $servers = Server::all('server_ip');
    	$campaigns = DB::table('calllogs')->distinct()->get('campaign');
    	$dispositions = DB::table('calllogs')->distinct()->get('dispo');
        $users = UserEmployeeMapping::orderBy('user_id')->get();

        $servers = $servers->isEmpty() ? $this->get_servers() : $servers;
        $campaigns = $campaigns->isEmpty() ? $this->get_campaigns() : $campaigns;
        $dispositions = $dispositions->isEmpty() ? $this->get_dispositions() : $dispositions;


    	// default from and to date
    	// $from_raw = new DateTime("yesterday", new DateTimeZone('Asia/Kuala_Lumpur'));
    	// $from_dt = $from_raw->format('m/d/Y g:i A');
    	// $to_dt = date('m/d/Y g:i A',strtotime('+23 hour +59 minutes',strtotime($from_dt)));

    	// return view('supervisor.index',compact('calllogs','teams','servers','campaigns','dispositions'));

        $sid = [];
        $campaign = [];
        $dispo = [];
        $from = '';
        $to = '';
        $user = -1;

        // if(empty($request->all()) || !empty($request->page)){
        if(empty($request->from)){
            $calllogs = CallLog::available_calllogs();

            foreach ($servers as $server) {
                array_push($sid, $server->server_ip);
            }

            foreach ($campaigns as $camp) {
                array_push($campaign, $camp->campaign);
            }

            foreach ($dispositions as $disposition) {
                array_push($dispo, $disposition->dispo);
            }
        }else{
            $from = $request->from;
            $to = $request->to;
            $sid = $request->sid;
            $campaign = $request->campaign;
            $dispo = $request->dispo;
            $user = $request->user;
            $calllogs = CallLog::search_call_logs($sid,$campaign,$dispo,$from,$to,$user);
            $calllogs->withPath(route('supervisor.index'));
        }

        return view('supervisor.index',compact('calllogs','teams','servers','campaigns','dispositions','users','sid','campaign','dispo','from','to','user'));
    }

    public function manage_teams(){
        $teams = Team::all();
        return view('supervisor.manage_teams',compact('teams'));
    }

   

    // public function assign_calls(Request $request){
    //     $validator = Validator::make($request->all(),[
    //         'calllogs' => 'required'
    //     ],[
    //         'calllogs.required' => 'No selected call logs'
    //     ]);

    //     if($validator->fails()){
    //         return response()->json(['errors'=>$validator->getMessageBag()->toArray()]);
    //     }else{
    //         $calllogs = $request->calllogs;
    //         foreach ($calllogs as $calllog) {
    //             $c = CallLog::find($calllog);
    //             if(empty($c)){
    //                 $c = CallLogArchive::find($calllog);
    //             }
    //             // make sure calllog is not yet assigned before assigning it
    //             if(!isset($c->team_code)){
    //                 $c->team_code = $request->assigned_team;
    //                 $c->save();
    //             }
    //         }
    //         return response()->json(['success'=>'Assigned call logs']);
    //     }
        
    // }

    public function assign_calls(Request $request){
        $validator = Validator::make($request->all(),[
            'calllogs' => 'required'
        ],[
            'calllogs.required' => 'No selected call logs'
        ]);

        if($validator->fails()){
            return response()->json(['errors'=>$validator->getMessageBag()->toArray()]);
        }else{
            $calllogs = $request->calllogs;
            foreach ($calllogs as $calllog) {
                $c = CallLog::find($calllog);
                if(empty($c)){
                    $c = CallLogArchive::find($calllog);
                }
                // make sure calllog is not yet assigned before assigning it
                if(!isset($c->team_code)){
                    $c->team_code = $request->assigned_team;
                    if($c->save()){
                        $assigned_call = new CallLogsAssigned;
                        $assigned_call->ctr                = $c->ctr;
                        $assigned_call->timestamp          = $c->timestamp;
                        $assigned_call->user               = $c->user;
                        $assigned_call->user_group         = $c->user_group;
                        $assigned_call->audit_type         = $c->audit_type;
                        $assigned_call->phone_number       = $c->phone_number;
                        $assigned_call->recording_id       = $c->recording_id;
                        $assigned_call->recording_filename = $c->recording_filename;
                        $assigned_call->recording_url      = $this->generate_recording_url($c)['url'];
                        $assigned_call->server_ip          = $c->server_ip;
                        $assigned_call->server_origin      = $c->server_origin;
                        $assigned_call->campaign           = $c->campaign;
                        $assigned_call->dispo              = $c->dispo;
                        $assigned_call->talk_time          = $c->talk_time;
                        $assigned_call->team_code          = $c->team_code;
                        $assigned_call->is_claimed         = $c->is_claimed;
                        $assigned_call->created_at         = $c->created_at;
                        $assigned_call->updated_at         = $c->updated_at;
                        $assigned_call->claimed_by         = $c->claimed_by;
                        $assigned_call->status             = $c->status;
                        $assigned_call->url_stage          = $this->get_url_stage($assigned_call->recording_url);

                        $assigned_call->save();
                    }
                }
            }
            return response()->json(['success'=>'Assigned call logs']);
        }
        
    }


    public function assign_preference(){
        $rules_list = AssignPreference::all();

        return view('supervisor.assign_preference',compact('rules_list'));
    }

    public function assign_preference_edit($id){
        $rule = AssignPreference::find($id);
        $teams = Team::all();
        $dispositions = Disposition::all();
        
        // $assign_pref_dispo = AssignPreferenceDisposition::where('assign_preference_id',$id);
        $assign_pref_dispo = $rule->assign_preference_dispositions;
        $dispo_list = [];
        foreach ($assign_pref_dispo as $disp) {
            $dispo_list[$disp->disposition_id] = $disp->count;
        }

        return view('supervisor.assign_preference_edit',compact('rule','dispositions','teams','dispo_list'));
    }

    public function assign_preference_update($id, Request $request){
        $assign_preference = AssignPreference::find($id);
        $assign_preference->name = $request->name;
        $assign_preference->team_id = $request->team_id;
        $assign_preference->updated_by = Auth::id();
        
        if($assign_preference->save()){
            $id = $assign_preference->id;
            $dispositions = $request->dispo;
            foreach ($dispositions as $dispo_id => $count) {
                $count = isset($count) ? $count : -1;
                $assign_pref_dispo = AssignPreferenceDisposition::updateOrCreate(
                    ['assign_preference_id' => $id,  'disposition_id' => $dispo_id],['count' => $count]
                );

                // echo "dispo: $dispo_id   , count: $count <br><br>";
            }
        }

        return redirect()->route('supervisor.assign_preference');
    }

    public function assign_preference_new(){
        $teams = Team::all();
        $dispositions = Disposition::all(); 

        return view('supervisor.assign_preference_new',compact('dispositions','teams'));
    }

    public function assign_preference_create(Request $request){
        // dd($request->all());
        $assign_preference = new AssignPreference;
        $assign_preference->name = $request->name;
        $assign_preference->team_id = $request->team_id;
        $assign_preference->created_by = Auth::id();
        $assign_preference->updated_by = Auth::id();

        if($assign_preference->save()){
            $id = $assign_preference->id;
            $dispositions = $request->dispo;
            foreach ($dispositions as $dispo_id => $count) {
                $assign_pref_dispo = new AssignPreferenceDisposition;
                $assign_pref_dispo->assign_preference_id = $id;
                $assign_pref_dispo->disposition_id = $dispo_id;
                $assign_pref_dispo->count = empty($count) ? -1 : $count;
                $assign_pref_dispo->save();
            }
        }

        return redirect()->route('supervisor.assign_preference');
    }


    private function get_servers(){
        // $servers = [
        //     (object) ['server_ip' => '38.102.225.152'],
        //     (object) ['server_ip' => '38.107.183.5'],
        //     (object) ['server_ip' => '38.102.225.153']
        // ];

        $servers = Server::all();        

        return $servers;
    }

resources/views/supervisor/assign_preference.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="box">
				<h4>Auto Assign Preference</h4>
				<hr>
				<a href="{{ route('supervisor.assign_preference_new') }}">New</a>
				<div class="table-responsive">
					<table class="table table-bordered">
						<thead class="thead-light">
							<tr class="text-center">
								<th>Assignment Name</th>
								<th>Created By</th>
								<th colspan="2"></th>
							</tr>
						</thead>
						<tbody>
							@if(count($rules_list))
								@foreach($rules_list as $rule)
									<tr class="text-center">
										<td>{{ $rule->name }}</td>
										<td>{{ $rule->created_by_user->email }}</td>
										<td>
											<a class="btn btn-primary" href="{{ route('supervisor.assign_preference_edit',['id'=>$rule->id]) }}">Edit</button>
										</td>
										<td></td>
									</tr>
								@endforeach
							@else
									<tr>
										<td colspan="4">No list found</td>
									</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/supervisor/assign_preference_edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="box pb-5">
				<form action="{{ route('supervisor.assign_preference_update',['id'=>$rule->id]) }}" method="post">
					@csrf
					<h4>Call Assignment Preference</h4>
					<hr>
					<h5>Rule Name</h5>
					<div class="row">
						<div class="col-md-4 col-sm-12 mb-3">
							<input type="text" name="name" class="form-control" value="{{ $rule->name }}" required>
						</div>
					</div>
					<h5>Teams</h5>
					<div class="row">
						<div class="col-md-4 col-sm-12 mb-3">
							<select class="form-control" name="team_id">
								@foreach($teams as $team)
									<option value="{{ $team->id }}" {{ $team->id == $rule->team_id ? 'selected' : '' }}>
										{{ $team->name }}
									</option>
								@endforeach
							</select>
						</div>
					</div>
					<hr>
					<h5 class="mb-3">Dispositions</h5>
					<p>Leave as blank if you want to assign all records for each disposition. Place 0 if you want to exclude a disposition filter.</p>
					<div class="d-flex flex-wrap" style="gap: 1rem">
						@foreach($dispositions as $dispo)
							<div class="form-group" style="width: 10ch">
								<label>{{ empty(trim($dispo->short_name)) ? '(BLANK)' : $dispo->short_name }}</label>
								<input type="number" name="dispo[{{ $dispo->id }}]" class="form-control" style="width: 10ch" value="{{ $dispo_list[$dispo->id] == -1 ? '' : $dispo_list[$dispo->id] }}">
							</div>
						@endforeach
					</div>
					<hr>
					<div class="d-flex justify-content-end">
						<div class="d-flex" style="gap: 1rem;">
							<span class="btn btn-secondary" onclick="window.history.back();">Cancel</span>
							<input class="btn btn-primary" type="submit" value="Update">
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/supervisor/assign_preference_new.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="box">
			<form action="{{ route('supervisor.assign_preference_create') }}" method="post">
				@csrf
				<h4>Call Assignment Preference</h4>
				<hr>
				<h5>Rule Name</h5>
				<div class="row">
					<div class="col-md-4 col-sm-12 mb-3">
						<input type="text" name="name" class="form-control" required>
					</div>
				</div>
				<h5>Teams</h5>
				<div class="row">
					<div class="col-md-4 col-sm-12 mb-3">
						<select class="form-control" name="team_id">
							@foreach($teams as $team)
								<option value="{{ $team->id }}">
									{{ $team->name }}
								</option>
							@endforeach
						</select>
					</div>
				</div>
				<hr>
				<h5 class="mb-3">Dispositions</h5>
				<p>Leave as blank if you want to assign all records for each disposition. Place 0 if you want to exclude a disposition filter.</p>
				<div class="d-flex flex-wrap" style="gap: 1rem">
					@foreach($dispositions as $dispo)
						<div class="form-group" style="width: 10ch">
							<label>{{ empty(trim($dispo->short_name)) ? '(BLANK)' : $dispo->short_name }}</label>
							<input type="number" name="dispo[{{ $dispo->id }}]" class="form-control" style="width: 10ch">
						</div>
					@endforeach
				</div>
				<hr>
				<div class="d-flex justify-content-end" style="gap: 1em;">
					<span class="btn btn-secondary" onclick="window.history.back();">Cancel</span>
					<input class="btn btn-primary" type="submit" value="Create">
				</div>
			</form>
		</div>
	</div>
</div>

@endsection

resources/views/supervisor/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="row">
		<div class="col-md-3">
			@include('supervisor.search-section')
		</div>
		<div class="col-md-8">
			@include('supervisor.tablecontent-section')
		</div>
	</div>

	<div class="gray-bg">
		<div class="d-flex flex-column align-items-center justify-content-center h-100">
			<div class="text-light">Please wait</div>
			<div>
				<div class="spinner-grow text-info"></div>
				<div class="spinner-grow text-info"></div>
				<div class="spinner-grow text-info"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/supervisor/manage_teams.blade.php
@extends('layouts.app')

@section('content')
	<div clas="row">

		<div class="bg-notif del-team-notif">
			<div class="card">
				<div class="card-header">
					Remove Team?
				</div>
				<div class="card-body">
					Are you sure you want to remove this team?
				</div>
				<div class="card-footer">
					<div class="d-flex justify-content-end">
						<button class="btn btn-primary del-team px-4 mr-3">Yes</button>
						<button class="btn btn-secondary cancel">Cancel</button>
					</div>
				</div>
			</div>
		</div>


		<div class="bg-notif add-team-notif">
			<div class="card form-width">
				<div class="card-header">Create New Team</div>
				<div class="card-body">
					<form action="{{ route('teams.store') }}" method="post">
						@csrf
						<div class="form-group">
							<label>Team Name</label>
							<input type="text" name="name" class="form-control">
						</div>
						<div class="form-group">
							<label>Short Description</label>
							<input type="text" name="short_desc" class="form-control">
						</div>
						<div class="d-flex justify-content-end">
							<button class="btn btn-primary mr-3">Create</button>
							<span class="btn btn-secondary cancel">Cancel</span>
						</div>
					</form>
				</div>
			</div>
		</div>


		<div class="col-md-10 mx-auto">

			@if($errors->any())
				<div class="alert alert-danger alert-dismissible fade show">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					The ff. error prevented the system from adding the team:
						<ul>
							@foreach($errors->all() as $error)
								<li>{{ $error }}</li>
							@endforeach
						</ul>
				</div>
			@endif

			@if (session('success'))
			    <div class="alert alert-success alert-dismissible fade show">
			    	<button type="button" class="close" data-dismiss="alert">&times;</button>
			        <strong>Success! </strong>{{ session('success') }}
			    </div>
			@endif

			<div class="box">
				<div class="d-flex">
					<h4 class="mr-auto">Teams</h4>
					<button class="btn btn-success add-team-trig">Add New Team</button>
				</div>
				<hr>
				<div>
					<table class="table table-bordered table-responsive w-100 d-block d-md-table">
						<thead>
							<tr class="thead-light">
								<th>Team Name</th>
								<th>Members (#)</th>
								<th>Description</th>
								<th>Created Date</th>
								<th colspan="2">Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach($teams as $team)
								<tr data-id="{{ $team->code }}">
									<td>{{ $team->name }}</td>
									<td>{{ $team->user_teams->count() }}</td>
									<td>{{ $team->short_desc }}</td>
									<td>{{ format_date($team->created_at) }}</td>
									<td class="text-center"><button class="btn btn-primary edit-team-trig">Edit</button></td>
									<td class="text-center"><button class="btn btn-secondary del-team-trg">Delete</button></td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/supervisor/search-section.blade.php
<div class="row mb-3">
	<div class="col-md-12">
		<div class="box">
			<h5>Call Logs Options</h5>
			<hr>
			<form class="calllogs-search" action="{{ route('supervisor.index') }}" method="GET">
				<div class="form-group">
					<label>From</label>
					<input type="date" class="form-control" name="from" value="{{ !empty($from) ? $from : '' }}" required>
				</div>
				<div class="form-group">
					<label>To</label>
					<input type="date" class="form-control" name="to" value="{{ !empty($to) ? $to : '' }}" required>
				</div>
				<div class="form-group">
					<label>Server Id</label>
					<select class="custom-select" name="sid[]" multiple>
						@foreach($servers as $server)
						<option value="{{ $server->server_ip }}" {{ in_array($server->server_ip, $sid) ? 'selected' : '' }}>
							{{ $server->server_ip }}
						</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label>Campaign</label>
					<select class="custom-select" name="campaign[]" multiple>
						@foreach($campaigns as $camp)
						<option value="{{ $camp->campaign }}" {{ in_array($camp->campaign, $campaign) ? 'selected' : '' }}>
							{{ $camp->campaign }}
						</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label>Dispo</label>
					<select class="custom-select" name="dispo[]" multiple>
						@foreach($dispositions as $disposition)
						<option value="{{ $disposition->dispo }}" {{ in_array($disposition->dispo, $dispo) ? 'selected' : '' }}>
							{{ $disposition->dispo }}
						</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<label>User</label>
					<select class="custom-select" name="user">
						<option value="-1">All</option>
						@foreach($users as $user)
						<option value="{{ $user->user_id }}">
							{{ $user->user_id  }}
						</option>
						@endforeach
					</select>
				</div>
				<div class="form-group">
					<button class="btn btn-primary">Search</button>
				</div>
			</form>
		</div>
	</div>
</div>

resources/views/supervisor/search.blade.php
@extends('layouts.app')

@section('content')
	<div class="row">
		<div class="col-md-3">
			@include('supervisor.search-section')
		</div>
		<div class="col-md-8">
			@include('supervisor.search_result-section')
		</div>
	</div>

	<div class="gray-bg">
		<div class="d-flex flex-column align-items-center justify-content-center h-100">
			<div class="text-light">Please wait</div>
			<div>
				<div class="spinner-grow text-info"></div>
				<div class="spinner-grow text-info"></div>
				<div class="spinner-grow text-info"></div>
			</div>
		</div>
	</div>
@endsection

resources/views/supervisor/search_result-section.blade.php
<div class="row">
	<div class="col-md-12">

		<div class="alert cl-alert" style="display: none;">
			<strong>Success!</strong><span></span>
		</div>

		<div class="box">
			<form class="calllog-form" action="{{ route('supervisor.assign_calls') }}" method="post">
				<div class="row mb-3">
					<div class="col-md-7 mb-2">
						<div class="d-flex align-items-start">
							<div class="input-group mr-2">
								<input type="number" class="form-control input-select-custom">
								<div class="input-group-append">
									<span class="btn btn-secondary select-custom">Select</span>
								</div>
							</div>
							<div class="btn btn-secondary w-75 mr-2 select-all">Select All</div>
							<div class="btn btn-secondary w-75 mr-2 deselect-all">Deselect All</div>
						</div>
					</div>
					<div class="col-md-3">
							<select class="custom-select" name="assigned_team">
								<optgroup label="Teams/Group">
									@foreach($teams as $team)
										<option value="{{ $team->code }}">
											{{ $team->name }}
										</option>
									@endforeach
								</optgroup>
							</select>
					</div>
					<div class="col-md-2">
						<button class="btn btn-primary">Assign</button>
					</div>
				</div>

				<div class="calllogs-list">
					<table class="table table-bordered table-responsive w-100 d-block d-md-table">
						<thead class="thead-dark">
							<tr>
								<th></th>
								<th>Recording Id</th>
								<th>Server Id</th>
								<th>Campaign</th>
								<th>Dispo</th>
								<th>Talk Time</th>
								<th>Date</th>
							</tr>
						</thead>
						<tbody>
							@if(count($calllogs))
								@foreach($calllogs as $calllog)
									<tr>
										<td class="text-center">
											<div class="app-checkbox d-inline-block">
												<input type="checkbox" 
													   name="calllogs[]"
													   id="cl-{{ $calllog->ctr }}"
													   value="{{ $calllog->ctr }}">
												<label class="checkmark" 
													   for="cl-{{ $calllog->ctr }}">   	
												</label>
											</div>
										</td>
										<td>{{ $calllog->recording_id }}</td>
										<td>{{ $calllog->server_ip }}</td>
										<td>{{ $calllog->campaign }}</td>
										<td>{{ $calllog->dispo }}</td>
										<td>{{ $calllog->talk_time }}</td>
										<td>{{ date_format(date_create($calllog->timestamp),'m/d/Y H:i A') }}</td>
									</tr>
								@endforeach
							@else
								<tr class="text-center">
									<td colspan="7">Empty results</td>
								</tr>
							@endif
						</tbody>
					</table>
					{{ $calllogs->links() }}
				</div>
			</form>
		</div>
	</div>
</div>